# Site settings
title: "minyoung's portfolio"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "MinYoung Hwang"
resume_title:                   "Welcome! If you want visit my github. Click the icon on the right"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hmylove01@naver.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-4845-3553"
resume_contact_address:         "대구 달서구 조암남로10"

resume_header_contact_info:     "대구 달서구 조암남로10 • 010-4845-3553 • hmylove01@naver.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello this is my portfolio. But not finished yet. Sorry:) </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
